name: mujing_nas
description: Minimal headless NAS service for the Mujing distributed library.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  crypto: ^3.0.7
  mime: ^2.1.0
  sqlite3: ^2.4.5
  unorm_dart: ^0.3.2
  xml: ^6.5.0
